apiVersion: v1
kind: Pod
metadata:
  name: local-model
  namespace: kubeflow-user-example-com
spec:
  volumes:
    - name: model-files
      persistentVolumeClaim:
        claimName: model-files-claim
  containers:
    - name: local-model
      image: python:3.9.20
      command: [ "sleep" ]
      args: [ "infinity" ]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "1"
      volumeMounts:
        - mountPath: "/pv/"
          name: model-files
  nodeSelector:
      kubernetes.io/hostname: node5