apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-ui
  namespace: kubeflow
spec:
  ingressClassName: nginx
  rules:
  - host: kubeflow.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ml-pipeline-ui
            port:
              number: 80
